### ISSUE TITLE
Happy Navaratri 

### ISSUE THREAD

**Issue by suman-shah** [suman-shah/How-To-create-some-common-stuff-in-web#42]
guyz it's festival time so let's create Happy Navaratri  wishing greeting card using Created Durga Ji using HTML & CSS

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.

**Comment by NazimFilzer** [comment]
Hey, i would like to work on some issues. Is there anything?
